<a href="https://colab.research.google.com/github/DiegoSReco/intro_python_para_economistas/blob/main/script_python_5_Analisis_Datos_Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **5. Introducci√≥n al manejo de datos con `Pandas`üêº Parte 2**

## **5.4 Importar y explorar diferentes tipos de datos**

#### **5.4.1 Conjuntos de datos de librer√≠as (Woolridge, Causal Data, Scikit-learn)**

En Python es posible importar diferentes tipos de conjuntos de datos utilizando librer√≠as como Woolridge, CausalData, Datareade etc. Estas herramientas nos permitir√°n acceder a conjuntos de datos estructurados provenientes de fuentes econ√≥micas, financieras y de aprendizaje autom√°tico.

* **Wooldridge**

Esta libreria nos permite utilizar 111 conjuntos  de datos los cuales son utilizados en los ejemplos del libro  ***J.M. Wooldridge (2019) Introductory Econometrics: A Modern Approach***.

In [ ]:
pip install wooldridge

Requirement already satisfied: wooldridge in /usr/local/lib/python3.11/dist-packages (0.4.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from wooldridge) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas->wooldridge) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->wooldridge) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->wooldridge) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->wooldridge) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->wooldridge) (1.17.0)

In [ ]:
import wooldridge as wd

print("\n### Wooldridge: Lista de Conjuntos de Datos Disponibles ###")
print(wd.data())

### Wooldridge: Lista de Conjuntos de Datos Disponibles ###
  J.M. Wooldridge (2019) Introductory Econometrics: A Modern Approach,
  Cengage Learning, 6th edition.

  401k       401ksubs    admnrev       affairs     airfare
  alcohol    apple       approval      athlet1     athlet2
  attend     audit       barium        beauty      benefits
  beveridge  big9salary  bwght         bwght2      campus
  card       catholic    cement        census2000  ceosal1
  ceosal2    charity     consump       corn        countymurders
  cps78_85   cps91       crime1        crime2      crime3
  crime4     discrim     driving       earns       econmath
  elem94_95  engin       expendshares  ezanders    ezunem
  fair       fertil1     fertil2       fertil3     fish
  fringe     gpa1        gpa2          gpa3        happiness
  hprice1    hprice2     hprice3       hseinv      htv
  infmrt     injury      intdef        intqrt      inven
  jtrain     jtrain2     jtrain3       kielmc      lawsch85
  loanapp    lowbrth     mathpnl       meap00_01   meap01
  meap93     meapsingle  minwage       mlb1        mroz
  murder     nbasal      nyse          okun        openness
  pension    phillips    pntsprd       prison      prminwge
  rdchem     rdtelec     recid         rental      return
  saving     sleep75     slp75_81      smoke       traffic1
  traffic2   twoyear     volat         vote1       vote2
  voucher    wage1       wage2         wagepan     wageprc
  wine
None

In [ ]:
#Cargar un conjunto de datos espec√≠fico

description_wagepan = wd.data('alcohol', description= True)

description_wagepan

name of dataset: alcohol
no of variables: 33
no of observations: 9822

+------------+----------------------------------------------------+
| variable   | label                                              |
+------------+----------------------------------------------------+
| abuse      | =1 if abuse alcohol                                |
| status     | out of workforce = 1; unemployed = 2, employed = 3 |
| unemrate   | state unemployment rate                            |
| age        | age in years                                       |
| educ       | years of schooling                                 |
| married    | =1 if married                                      |
| famsize    | family size                                        |
| white      | =1 if white                                        |
| exhealth   | =1 if in excellent health                          |
| vghealth   | =1 if in very good health                          |
| goodhealth | =1 if in good health                               |
| fairhealth | =1 if in fair health                               |
| northeast  | =1 if live in northeast                            |
| midwest    | =1 if live in midwest                              |
| south      | =1 if live in south                                |
| centcity   | =1 if live in central city of MSA                  |
| outercity  | =1 if in outer city of MSA                         |
| qrt1       | =1 if interviewed in first quarter                 |
| qrt2       | =1 if interviewed in second quarter                |
| qrt3       | =1 if interviewed in third quarter                 |
| beertax    | state excise tax, $ per gallon                     |
| cigtax     | state cigarette tax, cents per pack                |
| ethanol    | state per-capita ethanol consumption               |
| mothalc    | =1 if mother an alcoholic                          |
| fathalc    | =1 if father an alcoholic                          |
| livealc    | =1 if lived with alcoholic                         |
| inwf       | =1 if status > 1                                   |
| employ     | =1 if employed                                     |
| agesq      | age^2                                              |
| beertaxsq  | beertax^2                                          |
| cigtaxsq   | cigtax^2                                           |
| ethanolsq  | ethanol^2                                          |
| educsq     | educ^2                                             |
+------------+----------------------------------------------------+

Terza, J.V. (2002), ‚ÄúAlcohol Abuse and Employment: A Second Look,‚Äù
Journal of Applied Econometrics 17, 393-404. I obtained these data
from the Journal of Applied Econometrics data archive at
http://qed.econ.queensu.ca/jae/.

In [ ]:
df_wagepan = wd.data('wagepan')
df_wagepan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4360 entries, 0 to 4359
Data columns (total 44 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   nr        4360 non-null   int64
 1   year      4360 non-null   int64
 2   agric     4360 non-null   int64
 3   black     4360 non-null   int64
 4   bus       4360 non-null   int64
 5   construc  4360 non-null   int64
 6   ent       4360 non-null   int64
 7   exper     4360 non-null   int64
 8   fin       4360 non-null   int64
 9   hisp      4360 non-null   int64
 10  poorhlth  4360 non-null   int64
 11  hours     4360 non-null   int64
 12  manuf     4360 non-null   int64
 13  married   4360 non-null   int64
 14  min       4360 non-null   int64
 15  nrthcen   4360 non-null   int64
 16  nrtheast  4360 non-null   int64
 17  occ1      4360 non-null   int64
 18  occ2      4360 non-null   int64
 19  occ3      4360 non-null   int64
 20  occ4      4360 non-null   int64
 21  occ5      4360 non-null   int64
 22  occ6      4360 non-null   int64
 23  occ7      4360 non-null   int64
 24  occ8      4360 non-null   int64
 25  occ9      4360 non-null   int64
 26  per       4360 non-null   int64
 27  pro       4360 non-null   int64
 28  pub       4360 non-null   int64
 29  rur       4360 non-null   int64
 30  south     4360 non-null   int64
 31  educ      4360 non-null   int64
 32  tra       4360 non-null   int64
 33  trad      4360 non-null   int64
 34  union     4360 non-null   int64
 35  lwage     4360 non-null   float64
 36  d81       4360 non-null   int64
 37  d82       4360 non-null   int64
 38  d83       4360 non-null   int64
 39  d84       4360 non-null   int64
 40  d85       4360 non-null   int64
 41  d86       4360 non-null   int64
 42  d87       4360 non-null   int64
 43  expersq   4360 non-null   int64
dtypes: float64(1), int64(43)
memory usage: 1.5 MB

* **Causal Data**

[El Efecto: Una Indtroducci√≥n al Dise√±o de Investigaci√≥n y Causalidad](https://theeffectbook.net/)

In [ ]:
pip install causaldata

Collecting causaldata
  Downloading causaldata-0.1.5.tar.gz (2.7 MB)
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 2.7/2.7 MB 26.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: statsmodels in /usr/local/lib/python3.11/dist-packages (from causaldata) (0.14.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from causaldata) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas->causaldata) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->causaldata) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->causaldata) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->causaldata) (2025.1)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /usr/local/lib/python3.11/dist-packages (from statsmodels->causaldata) (1.14.1)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels->causaldata) (1.0.1)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.11/dist-packages (from statsmodels->causaldata) (24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->causaldata) (1.17.0)
Building wheels for collected packages: causaldata
  Building wheel for causaldata (setup.py) ... done
  Created wheel for causaldata: filename=causaldata-0.1.5-py3-none-any.whl size=2767647 sha256=6d699438947f56673f0f6ff28841121c033b5ac39f367c77e3fc29939bde2e4f
  Stored in directory: /root/.cache/pip/wheels/a1/03/f7/4feb3ae1964932dc58fe5acfc4bdb02d5df05dd6b8aa2d8437
Successfully built causaldata
Installing collected packages: causaldata
Successfully installed causaldata-0.1.5

In [ ]:
import causaldata
print(dir(causaldata))

['Mroz', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'abortion', 'adult_services', 'auto', 'avocado', 'black_politicians', 'castle', 'close_college', 'close_elections_lmb', 'cps_mixtape', 'credit_cards', 'gapminder', 'google_stock', 'gov_transfers', 'gov_transfers_density', 'greek_data', 'mortgages', 'nhefs', 'nhefs_codebook', 'nhefs_complete', 'nsw_mixtape', 'organ_donations', 'restaurant_inspections', 'ri', 'scorecard', 'snow', 'social_insure', 'texas', 'thornton_hiv', 'titanic', 'training_bias_reduction', 'training_example', 'yule']

**Carga de datos en Causal Data**

In [ ]:
#Carga de datos
df_organs = causaldata.organ_donations.load_pandas().data

In [ ]:
print(df_organs.info())
print(df_organs.describe())
df_organs

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   State        162 non-null    object
 1   Quarter      162 non-null    object
 2   Rate         162 non-null    float64
 3   Quarter_Num  162 non-null    int64
dtypes: float64(1), int64(1), object(2)
memory usage: 5.2+ KB
None
             Rate  Quarter_Num
count  162.000000   162.000000
mean     0.445048     3.500000
std      0.153353     1.713121
min      0.122900     1.000000
25%      0.334600     2.000000
50%      0.439700     3.500000
75%      0.564450     5.000000
max      0.790000     6.000000

       State Quarter    Rate  Quarter_Num
0     Alaska  Q42010  0.7500            1
1     Alaska  Q12011  0.7700            2
2     Alaska  Q22011  0.7700            3
3     Alaska  Q32011  0.7800            4
4     Alaska  Q42011  0.7800            5
..       ...     ...     ...          ...
157  Wyoming  Q12011  0.5946            2
158  Wyoming  Q22011  0.5937            3
159  Wyoming  Q32011  0.5911            4
160  Wyoming  Q42011  0.5854            5
161  Wyoming  Q12012  0.5881            6

[162 rows x 4 columns]

**Fuente del data set**

In [ ]:
#Fuente del data set
print(causaldata.organ_donations.DESCRLONG)
print(causaldata.organ_donations.SOURCE)

The organ_donation data contains data from Kessler and Roth (2014) on organ donation rates by state and quarter. The state of California enacted an active-choice phrasing for their organ donation sign-up questoin in Q32011. The only states included in the data are California and those that can serve as valid controls; see Kessler and Roth (2014). This data set is used in the Difference-in-Differences chapter of The Effect.

Kessler, J.B. and Roth, A.E., 2014. Don't take 'no' for an answer: An experiment with actual organ donor registrations. National Bureau of Economic Research working paper No. 20378. https://www.nber.org/papers/w20378

In [ ]:
#Fuente del data set
print(causaldata.credit_cards.DESCRLONG)
print(causaldata.credit_cards.SOURCE)

Data from the UCI Machine Learning Repository on Taiwanese credit card holders, the amount of their credit card bill, and whether their payment was late. This data is used in the Matching chapter of The Effect by Huntington-Klein.

Lichman, Moshe. 2013. UCI Machine Learning Repository.

In [ ]:
df_cc = causaldata.credit_cards.load_pandas().data
df_cc

       LateSept  LateApril  BillApril  AGE
0             1          0      0.000   24
1             0          1      3.261   26
2             0          0     15.549   34
3             0          0     29.547   37
4             0          0     19.131   57
...         ...        ...        ...  ...
29995         0          0     15.980   39
29996         0          0      0.000   43
29997         1          0     19.357   37
29998         1          0     48.944   41
29999         0          0     15.313   46

[30000 rows x 4 columns]

* **Scikit-learn**

Modelos de regressi√≥n y clasificaci√≥n para an√°lisis predictivo de datos.

[Scikit-learn](https://scikit-learn.org/stable/)


* load_iris(): Datos de clasificaci√≥n de flores Iris.

* load_digits(): Im√°genes de d√≠gitos escritos a mano.

* load_wine(): Caracter√≠sticas qu√≠micas de vinos.

* fetch_california_housing(): Datos de viviendas en California.

In [ ]:
from sklearn import datasets
import pandas as pd

In [ ]:
calif_hs = datasets.fetch_california_housing()
print(calif_hs)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [ ]:
calif_hs.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [ ]:
df_calif_hs = pd.DataFrame(data= calif_hs.data,
                           columns = calif_hs.feature_names)
df_calif_hs

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [ ]:
# Acceder a caracter√≠sticas del dataset
print(df_calif_hs.info())
print(df_calif_hs.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB
None
             MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000
mean       3.870671     28.639486      5.429000      1.096675   1425.476744
std        1.899822     12.585558      2.474173      0.473911   1132.462122
min        0.499900      1.000000      0.846154      0.333333      3.000000
25%        2.563400     18.000000      4.440716      1.006079    787.000000
50%        3.534800     29.000000      5.229129      1.048780   1166.000000
75%        4.743250     37.000000      6.052381      1.099526   1725.000000
max       15.000100     52.000000    141.909091     34.066667  35682.000000

           AveOccup      Latitude     Longitude
count  20640.000000  20640.000000  20640.000000
mean       3.070655     35.631861   -119.569704
std       10.386050      2.135952      2.003532
min        0.692308     32.540000   -124.350000
25%        2.429741     33.930000   -121.800000
50%        2.818116     34.260000   -118.490000
75%        3.282261     37.710000   -118.010000
max     1243.333333     41.950000   -114.310000

* **DataReader**

Paqueter√≠a que nos permite acceder de forma f√°cil y flexible a fuentes de datos:

* Yahoo Finance para datos de acciones
* Banco Mundial para indicadores econ√≥micos
* Tasas de cambio de divisas
* √çndices burs√°tiles como S&P 500 y NASDAQ

**Beneficios**

- Acceso f√°cil a datos financieros
- Descarga autom√°tica de informaci√≥n actualizada
- Integraci√≥n directa con Pandas para an√°lisis

**Ejemplos:**

- **Banco Mundial**

In [1]:
import pandas_datareader as pdr
#from datetime import datetime
import pandas_datareader.wb as wb

In [2]:
df_meta_wb = wb.search('')

print(df_meta_wb['topics'].value_counts().head(10))

#Filtramos DF  relaciones con probreza
df_meta_wb[(df_meta_wb['topics'] == 'Economy & Growth') & df_meta_wb['name'].str.contains('GDP') ]

topics
                             17502
Social Protection & Labor     2042
Health                         568
Education                      527
External Debt                  485
Economy & Growth               209
Financial Sector               171
Poverty                        138
Public Sector                  133
Gender                         123
Name: count, dtype: int64

,id,name,unit,source,sourceNote,sourceOrganization,topics
688,6.0.GDP_current,GDP (current $),,LAC Equity Lab,GDP is the sum of gross value added by all res...,b'World Development Indicators (World Bank)',Economy & Growth
689,6.0.GDP_growth,GDP growth (annual %),,LAC Equity Lab,Annual percentage growth rate of GDP at market...,b'World Development Indicators (World Bank)',Economy & Growth
690,6.0.GDP_usd,GDP (constant 2005 $),,LAC Equity Lab,GDP is the sum of gross value added by all res...,b'World Development Indicators (World Bank)',Economy & Growth
691,6.0.GDPpc_constant,"GDP per capita, PPP (constant 2011 internation...",,LAC Equity Lab,GDP per capita based on purchasing power parit...,b'World Development Indicators (World Bank)',Economy & Growth
1929,BN.CAB.XOKA.GD.ZS,Current account balance (% of GDP),,World Development Indicators,Current account balance is the sum of net expo...,"b'International Monetary Fund, Balance of Paym...",Economy & Growth
1959,BN.KLT.PRVT.GD.ZS,"Private capital flows, total (% of GDP)",,Africa Development Indicators,Private capital flows consist of net foreign d...,"b'International Monetary Fund, Balance of Paym...",Economy & Growth
10649,NE.CON.GOVT.ZS,General government final consumption expenditu...,,World Development Indicators,General government final consumption expenditu...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10660,NE.CON.PETC.ZS,"Household final consumption expenditure, etc. ...",,WDI Database Archives,Household final consumption expenditure (forme...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10677,NE.CON.PRVT.ZS,Households and NPISHs final consumption expend...,,World Development Indicators,Household final consumption expenditure (forme...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10687,NE.CON.TETC.ZS,"Final consumption expenditure, etc. (% of GDP)",,WDI Database Archives,Final consumption expenditure (formerly total ...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10696,NE.CON.TOTL.ZS,Final consumption expenditure (% of GDP),,World Development Indicators,Final consumption expenditure (formerly total ...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10706,NE.DAB.TOTL.ZS,Gross national expenditure (% of GDP),,World Development Indicators,Gross national expenditure (formerly domestic ...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10752,NE.GDI.FPRV.ZS,"Gross fixed capital formation, private sector ...",,World Development Indicators,Private investment covers gross outlays by the...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10768,NE.GDI.FTOT.ZS,Gross fixed capital formation (% of GDP),,World Development Indicators,Gross fixed capital formation (formerly gross ...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10798,NE.GDI.TOTL.ZS,Gross capital formation (% of GDP),,World Development Indicators,Gross capital formation (formerly gross domest...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10875,NV.IND.MANF.ZS,"Manufacturing, value added (% of GDP)",,World Development Indicators,Manufacturing refers to industries belonging t...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10890,NV.IND.TOTL.ZS,"Industry (including construction), value added...",,World Development Indicators,Industry (including construction) corresponds ...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10928,NV.SRV.TETC.ZS,"Services, etc., value added (% of GDP)",,WDI Database Archives,Services correspond to ISIC divisions 50-99 an...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10934,NV.SRV.TOTL.ZS,"Services, value added (% of GDP)",,World Development Indicators,Services correspond to ISIC divisions 50-99 an...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11123,NY.GDP.DEFL.KD.ZG,"Inflation, GDP deflator (annual %)",,World Development Indicators,Inflation as measured by the annual growth rat...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11125,NY.GDP.DEFL.ZS,GDP deflator (base year varies by country),,World Development Indicators,The GDP implicit deflator is the ratio of GDP ...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11129,NY.GDP.DISC.CN,Discrepancy in expenditure estimate of GDP (cu...,,World Development Indicators,Discrepancy in expenditure estimate of GDP is ...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11130,NY.GDP.DISC.KN,Discrepancy in expenditure estimate of GDP (co...,,World Development Indicators,A statistical discrepancy usually arises when ...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11139,NY.GDP.MKTP.CD,GDP (current US$),,World Development Indicators,GDP at purchaser's prices is the sum of gross ...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11141,NY.GDP.MKTP.CN,GDP (current LCU),,World Development Indicators,GDP at purchaser's prices is the sum of gross ...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11142,NY.GDP.MKTP.CN.AD,GDP: linked series (current LCU),,World Development Indicators,GDP is the sum of gross value added by all res...,b'World Bank staff estimates based on World Ba...,Economy & Growth
11145,NY.GDP.MKTP.KD,GDP (constant 2015 US$),,World Development Indicators,GDP at purchaser's prices is the sum of gross ...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11147,NY.GDP.MKTP.KD.ZG,GDP growth (annual %),,World Development Indicators,Annual percentage growth rate of GDP at market...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11148,NY.GDP.MKTP.KN,GDP (constant LCU),,World Development Indicators,GDP is the sum of gross value added by all res...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11151,NY.GDP.MKTP.PP.CD,"GDP, PPP (current international $)",,World Development Indicators,This indicator provides values for gross domes...,"b'International Comparison Program, World Bank...",Economy & Growth
11152,NY.GDP.MKTP.PP.KD,"GDP, PPP (constant 2021 international $)",,World Development Indicators,PPP GDP is gross domestic product converted to...,"b'International Comparison Program, World Bank...",Economy & Growth
11158,NY.GDP.PCAP.CD,GDP per capita (current US$),,World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11159,NY.GDP.PCAP.CN,GDP per capita (current LCU),,World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11160,NY.GDP.PCAP.KD,GDP per capita (constant 2015 US$),,World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11161,NY.GDP.PCAP.KD.ZG,GDP per capita growth (annual %),,World Development Indicators,Annual percentage growth rate of GDP per capit...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11162,NY.GDP.PCAP.KN,GDP per capita (constant LCU),,World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11163,NY.GDP.PCAP.PP.CD,"GDP per capita, PPP (current international $)",,World Development Indicators,This indicator provides per capita values for ...,"b'International Comparison Program, World Bank...",Economy & Growth
11164,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",,World Development Indicators,GDP per capita based on purchasing power parit...,"b'International Comparison Program, World Bank...",Economy & Growth
11181,NY.GDS.TOTL.ZS,Gross domestic savings (% of GDP),,World Development Indicators,Gross domestic savings are calculated as GDP l...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11226,NY.GNS.ICTR.ZS,Gross savings (% of GDP),,World Development Indicators,Gross savings are calculated as gross national...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
11290,PA.NUS.PPP,"PPP conversion factor, GDP (LCU per internatio...",,World Development Indicators,Purchasing power parity (PPP) conversion facto...,"b'International Comparison Program, World Bank...",Economy & Growth
11291,PA.NUS.PPP.05,"2005 PPP conversion factor, GDP (LCU per inter...",,WDI Database Archives,Purchasing power parity conversion factor is t...,"b'World Bank, International Comparison Program...",Economy & Growth
11292,PA.NUS.PPPC.RF,Price level ratio of PPP conversion factor (GD...,,World Development Indicators,Price level ratio is the ratio of a purchasing...,"b'International Comparison Program, World Bank...",Economy & Growth

In [ ]:
# Ejemplo 1: Recuperar datos econ√≥micos del Banco Mundial
df_pob_tot = wb.download( indicator= 'SP.POP.TOTL')
df_pob_tot

<ipython-input-48-8583881654db>:2: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_pob_tot = wb.download( indicator= 'SP.POP.TOTL')

                    SP.POP.TOTL
country       year
Canada        2005     32242732
              2004     31938807
              2003     31642461
Mexico        2005    105811504
              2004    104394131
              2003    102978515
United States 2005    295516599
              2004    292805298
              2003    290107933

In [ ]:
#Lista de paises en Latam
abv_latam = ["ARG", "BOL", "BRA", "CHL", "COL", "CRI", "CUB", "DOM", "ECU",
             "SLV", "GTM", "HND", "MEX", "NIC", "PAN", "PRY", "PER", "PRI",
             "URY", "VEN"]


#Poblacion total de paises
df_pob_tot_LA = wb.download( indicator= ['SP.POP.TOTL',
                                         'SI.POV.GINI',
                                         'NY.GDP.MKTP.KD'],
                              country= abv_latam ,
                              start= 2010,
                              end= 2023)
#Reset index
df_pob_tot_LA = df_pob_tot_LA.reset_index()
#Cambiar nombres de columnas
df_pob_tot_LA.rename(columns = {'SP.POP.TOTL': 'Poblacion total', 'SI.POV.GINI':'Gini', 'NY.GDP.MKTP.KD':'GDP'})

<ipython-input-82-57b332eb45bd>:8: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_pob_tot_LA = wb.download( indicator= ['SP.POP.TOTL',

           country  year  Poblacion total  Gini           GDP
0        Argentina  2010         41288694  43.7  5.527382e+11
1        Argentina  2011         41730660  42.7  5.859243e+11
2        Argentina  2012         42161721  41.4  5.799102e+11
3        Argentina  2013         42582455  41.1  5.938590e+11
4        Argentina  2014         43024071  41.8  5.789376e+11
..             ...   ...              ...   ...           ...
275  Venezuela, RB  2019         28938098   NaN           NaN
276  Venezuela, RB  2020         28444077   NaN           NaN
277  Venezuela, RB  2021         28237826   NaN           NaN
278  Venezuela, RB  2022         28213017   NaN           NaN
279  Venezuela, RB  2023         28300854   NaN           NaN

[280 rows x 5 columns]

In [ ]:
df_pob_tot_LA[ df_pob_tot_LA['country'].isin(['Mexico', 'Argentina', 'Colombia'])  ]

       country  year  SP.POP.TOTL  SI.POV.GINI  NY.GDP.MKTP.KD
0    Argentina  2010     41288694         43.7    5.527382e+11
1    Argentina  2011     41730660         42.7    5.859243e+11
2    Argentina  2012     42161721         41.4    5.799102e+11
3    Argentina  2013     42582455         41.1    5.938590e+11
4    Argentina  2014     43024071         41.8    5.789376e+11
5    Argentina  2015     43477012          NaN    5.947493e+11
6    Argentina  2016     43900313         42.3    5.823766e+11
7    Argentina  2017     44288894         41.4    5.987909e+11
8    Argentina  2018     44654882         41.7    5.831181e+11
9    Argentina  2019     44973465         43.3    5.714507e+11
10   Argentina  2020     45191965         42.7    5.148743e+11
11   Argentina  2021     45312281         42.4    5.686366e+11
12   Argentina  2022     45407904         40.7    5.986030e+11
13   Argentina  2023     45538401          NaN    5.889595e+11
56    Colombia  2010     44777319         54.6    2.334799e+11
57    Colombia  2011     45259614         53.5    2.497019e+11
58    Colombia  2012     45715810         52.6    2.594718e+11
59    Colombia  2013     46151584         52.6    2.727931e+11
60    Colombia  2014     46565429         52.5    2.850661e+11
61    Colombia  2015     46969940         51.0    2.934924e+11
62    Colombia  2016     47437512         50.6    2.996187e+11
63    Colombia  2017     48131078         49.7    3.036916e+11
64    Colombia  2018     49024465         50.4    3.114792e+11
65    Colombia  2019     49907985         51.3    3.214056e+11
66    Colombia  2020     50629997         53.5    2.983097e+11
67    Colombia  2021     51188173         55.1    3.305307e+11
68    Colombia  2022     51737944         54.8    3.546227e+11
69    Colombia  2023     52321152          NaN    3.567873e+11
168     Mexico  2010    113623895         47.7    1.066822e+12
169     Mexico  2011    115243504          NaN    1.103564e+12
170     Mexico  2012    116818208         49.6    1.142776e+12
171     Mexico  2013    118343573          NaN    1.152514e+12
172     Mexico  2014    119784261         48.9    1.181370e+12
173     Mexico  2015    121072306          NaN    1.213294e+12
174     Mexico  2016    122251351         46.9    1.234800e+12
175     Mexico  2017    123400057          NaN    1.257912e+12
176     Mexico  2018    124573711         46.0    1.282719e+12
177     Mexico  2019    125762982          NaN    1.277682e+12
178     Mexico  2020    126799054         44.6    1.170944e+12
179     Mexico  2021    127648148          NaN    1.241768e+12
180     Mexico  2022    128613117         43.5    1.287579e+12
181     Mexico  2023    129739759          NaN    1.328781e+12

* **FRED: Federal Reserve bank of St. Louis logo**

In [13]:
#import pandas_datareader.fred as fred
from datetime import datetime
start_date = datetime(2023, 1, 1)
end_date = datetime(2025, 1, 1)

# Descargar los datos de FRED
series_unrate = pdr.get_data_fred('UNRATE', start=start_date, end=end_date)

# Mostrar las primeras filas
print(series_unrate)

            UNRATE
DATE
2023-01-01     3.5
2023-02-01     3.6
2023-03-01     3.5
2023-04-01     3.4
2023-05-01     3.6
2023-06-01     3.6
2023-07-01     3.5
2023-08-01     3.7
2023-09-01     3.8
2023-10-01     3.9
2023-11-01     3.7
2023-12-01     3.8
2024-01-01     3.7
2024-02-01     3.9
2024-03-01     3.9
2024-04-01     3.9
2024-05-01     4.0
2024-06-01     4.1
2024-07-01     4.2
2024-08-01     4.2
2024-09-01     4.1
2024-10-01     4.1
2024-11-01     4.2
2024-12-01     4.1
2025-01-01     4.0

In [14]:
#indicadores
series = ['CPIAUCSL', 'UNRATE', 'GDP']

#DF download
df_EU_ind = pdr.get_data_fred(series,
                         start=start_date,
                         end=end_date)

#DF
df_EU_ind

            CPIAUCSL  UNRATE        GDP
DATE
2023-01-01   300.456     3.5  27164.359
2023-02-01   301.476     3.6        NaN
2023-03-01   301.643     3.5        NaN
2023-04-01   302.858     3.4  27453.815
2023-05-01   303.316     3.6        NaN
2023-06-01   304.099     3.6        NaN
2023-07-01   304.615     3.5  27967.697
2023-08-01   306.138     3.7        NaN
2023-09-01   307.374     3.8        NaN
2023-10-01   307.653     3.9  28296.967
2023-11-01   308.087     3.7        NaN
2023-12-01   308.735     3.8        NaN
2024-01-01   309.794     3.7  28624.069
2024-02-01   311.022     3.9        NaN
2024-03-01   312.107     3.9        NaN
2024-04-01   313.016     3.9  29016.714
2024-05-01   313.140     4.0        NaN
2024-06-01   313.131     4.1        NaN
2024-07-01   313.566     4.2  29374.914
2024-08-01   314.131     4.2        NaN
2024-09-01   314.851     4.1        NaN
2024-10-01   315.564     4.1  29719.647
2024-11-01   316.449     4.2        NaN
2024-12-01   317.603     4.1        NaN
2025-01-01   319.086     4.0        NaN

**Extracci√≥n de Datos Financieros con `yfinance`**

Este paquete es muy √∫til para obtener informaci√≥n detallada sobre acciones, ETFs, divisas, y m√°s, con solo unas l√≠neas de c√≥digo.

In [17]:
import yfinance as yf

1 . Con yfinance, cada activo financiero se representa como un objeto llamado **Ticker**.

Este objeto nos permite acceder a la informaci√≥n detallada de la acci√≥n (o cualquier otro instrumento financiero).

In [24]:
stock_google = yf.Ticker("GOOGL")

print(stock_google)

yfinance.Ticker object <GOOGL>

El m√©todo `history()` nos permite obtener los precios hist√≥ricos de una acci√≥n, que incluye las columnas de apertura (Open), cierre (Close), m√°ximo (High), m√≠nimo (Low), volumen (Volume) y cierre ajustado (Adj Close).

In [31]:
#1Y
historical_data = stock_google.history(period="1mo")

#Podemos cambiar el par√°metro:'1d', '1mo', '1y', '5y'


# Tipo y datos
print(type(historical_data))
historical_data.info()

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 21 entries, 2025-02-26 00:00:00-05:00 to 2025-03-26 00:00:00-04:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          21 non-null     float64
 1   High          21 non-null     float64
 2   Low           21 non-null     float64
 3   Close         21 non-null     float64
 4   Volume        21 non-null     int64
 5   Dividends     21 non-null     float64
 6   Stock Splits  21 non-null     float64
dtypes: float64(6), int64(1)
memory usage: 1.3 KB

**Datos de Finanzas y Reportes de la Empresa**

Reportes de la empresa, como el balance general, la cuenta de resultados (ingresos y ganancias) y el flujo de caja.

In [34]:
#Estados de resultados
df_income_statement = stock_google.financials

# Mostrar el estado de resultados
print(df_income_statement)

                                                        2024-12-31  \
Tax Effect Of Unusual Items                            370968000.0
Tax Rate For Calcs                                           0.164
Normalized EBITDA                                   133132000000.0
Total Unusual Items                                   2262000000.0
Total Unusual Items Excluding Goodwill                2262000000.0
Net Income From Continuing Operation Net Minori...  100118000000.0
Reconciled Depreciation                              15311000000.0
Reconciled Cost Of Revenue                          146306000000.0
EBITDA                                              135394000000.0
EBIT                                                120083000000.0
Net Interest Income                                   4214000000.0
Interest Expense                                       268000000.0
Interest Income                                       4482000000.0
Normalized Income                                    98226968000.0
Net Income From Continuing And Discontinued Ope...  100118000000.0
Total Expenses                                      237628000000.0
Total Operating Income As Reported                  112390000000.0
Diluted Average Shares                                         NaN
Basic Average Shares                                           NaN
Diluted EPS                                                    NaN
Basic EPS                                                      NaN
Diluted NI Availto Com Stockholders                 100118000000.0
Net Income Common Stockholders                      100118000000.0
Net Income                                          100118000000.0
Net Income Including Noncontrolling Interests       100118000000.0
Net Income Continuous Operations                    100118000000.0
Tax Provision                                        19697000000.0
Pretax Income                                       119815000000.0
Other Income Expense                                  3211000000.0
Other Non Operating Income Expenses                   1137000000.0
Special Income Charges                                         NaN
Earnings From Equity Interest                         -188000000.0
Gain On Sale Of Security                              2262000000.0
Net Non Operating Interest Income Expense             4214000000.0
Interest Expense Non Operating                         268000000.0
Interest Income Non Operating                         4482000000.0
Operating Income                                    112390000000.0
Operating Expense                                    91322000000.0
Research And Development                             49326000000.0
Selling General And Administration                   41996000000.0
Selling And Marketing Expense                        27808000000.0
General And Administrative Expense                   14188000000.0
Other Gand A                                         14188000000.0
Gross Profit                                        203712000000.0
Cost Of Revenue                                     146306000000.0
Total Revenue                                       350018000000.0
Operating Revenue                                   350018000000.0

                                                        2023-12-31  \
Tax Effect Of Unusual Items                           -286479000.0
Tax Rate For Calcs                                           0.139
Normalized EBITDA                                   100032000000.0
Total Unusual Items                                  -2061000000.0
Total Unusual Items Excluding Goodwill               -2061000000.0
Net Income From Continuing Operation Net Minori...   73795000000.0
Reconciled Depreciation                              11946000000.0
Reconciled Cost Of Revenue                          133332000000.0
EBITDA                                               97971000000.0
EBIT                                                 86025000000.0
Net Interest Income                                   3557000000.0
Interest Expense                                       308000000.0
Interest Income                                       3865000000.0
Normalized Income                                    75569521000.0
Net Income From Continuing And Discontinued Ope...   73795000000.0
Total Expenses                                      223101000000.0
Total Operating Income As Reported                   84293000000.0
Diluted Average Shares                               12722000000.0
Basic Average Shares                                 12630000000.0
Diluted EPS                                                    5.8
Basic EPS                                                     5.84
Diluted NI Availto Com Stockholders                  73795000000.0
Net Income Common Stockholders                       73795000000.0
Net Income                                           73795000000.0
Net Income Including Noncontrolling Interests        73795000000.0
Net Income Continuous Operations                     73795000000.0
Tax Provision                                        11922000000.0
Pretax Income                                        85717000000.0
Other Income Expense                                 -2133000000.0
Other Non Operating Income Expenses                    556000000.0
Special Income Charges                                         NaN
Earnings From Equity Interest                         -628000000.0
Gain On Sale Of Security                             -2061000000.0
Net Non Operating Interest Income Expense             3557000000.0
Interest Expense Non Operating                         308000000.0
Interest Income Non Operating                         3865000000.0
Operating Income                                     84293000000.0
Operating Expense                                    89769000000.0
Research And Development                             45427000000.0
Selling General And Administration                   44342000000.0
Selling And Marketing Expense                        27917000000.0
General And Administrative Expense                   16425000000.0
Other Gand A                                         16425000000.0
Gross Profit                                        174062000000.0
Cost Of Revenue                                     133332000000.0
Total Revenue                                       307394000000.0
Operating Revenue                                   307394000000.0

                                                        2022-12-31  \
Tax Effect Of Unusual Items                           -981507000.0
Tax Rate For Calcs                                           0.159
Normalized EBITDA                                    91333000000.0
Total Unusual Items                                  -6173000000.0
Total Unusual Items Excluding Goodwill               -6173000000.0
Net Income From Continuing Operation Net Minori...   59972000000.0
Reconciled Depreciation                              13475000000.0
Reconciled Cost Of Revenue                          126203000000.0
EBITDA                                               85160000000.0
EBIT                                                 71685000000.0
Net Interest Income                                   1817000000.0
Interest Expense                                       357000000.0
Interest Income                                       2174000000.0
Normalized Income                                    65163493000.0
Net Income From Continuing And Discontinued Ope...   59972000000.0
Total Expenses                                      207994000000.0
Total Operating Income As Reported                   74842000000.0
Diluted Average Shares                               13159000000.0
Basic Average Shares                                 13063000000.0
Diluted EPS                                                   4.56
Basic EPS                                                     4.59
Diluted NI Availto Com Stockholders                  59972000000.0
Net Income Common Stockholders                       59972000000.0
Net Income                                           59972000000.0
Net Income Including Noncontrolling Interests        59972000000.0
Net Income Continuous Operations                     59972000000.0
Tax Provision                                        11356000000.0
Pretax Income                                        71328000000.0
Other Income Expense                                 -5331000000.0
Other Non Operating Income Expenses                   1179000000.0
Special Income Charges                                         NaN
Earnings From Equity Interest                         -337000000.0
Gain On Sale Of Security                             -6173000000.0
Net Non Operating Interest Income Expense             1817000000.0
Interest Expense Non Operating                         357000000.0
Interest Income Non Operating                         2174000000.0
Operating Income                                     74842000000.0
Operating Expense                                    81791000000.0
Research And Development                             39500000000.0
Selling General And Administration                   42291000000.0
Selling And Marketing Expense                        26567000000.0
General And Administrative Expense                   15724000000.0
Other Gand A                                         15724000000.0
Gross Profit                                        156633000000.0
Cost Of Revenue                                     126203000000.0
Total Revenue                                       282836000000.0
Operating Revenue                                   282836000000.0

                                                        2021-12-31  \
Tax Effect Of Unusual Items                           1948860000.0
Tax Rate For Calcs                                           0.162
Normalized EBITDA                                    91491000000.0
Total Unusual Items                                  12030000000.0
Total Unusual Items Excluding Goodwill               12030000000.0
Net Income From Continuing Operation Net Minori...   76033000000.0
Reconciled Depreciation                              12441000000.0
Reconciled Cost Of Revenue                          110939000000.0
EBITDA                                              103521000000.0
EBIT                                                 91080000000.0
Net Interest Income                                   1153000000.0
Interest Expense                                       346000000.0
Interest Income                                       1499000000.0
Normalized Income                                    65951860000.0
Net Income From Continuing And Discontinued Ope...   76033000000.0
Total Expenses                                      178923000000.0
Total Operating Income As Reported                   78714000000.0
Diluted Average Shares                               13553000000.0
Basic Average Shares                                 13353000000.0
Diluted EPS                                                   5.61
Basic EPS                                                     5.69
Diluted NI Availto Com Stockholders                  76033000000.0
Net Income Common Stockholders                       76033000000.0
Net Income                                           76033000000.0
Net Income Including Noncontrolling Interests        76033000000.0
Net Income Continuous Operations                     76033000000.0
Tax Provision                                        14701000000.0
Pretax Income                                        90734000000.0
Other Income Expense                                 10867000000.0
Other Non Operating Income Expenses                  -1497000000.0
Special Income Charges                                         0.0
Earnings From Equity Interest                          334000000.0
Gain On Sale Of Security                             12030000000.0
Net Non Operating Interest Income Expense             1153000000.0
Interest Expense Non Operating                         346000000.0
Interest Income Non Operating                         1499000000.0
Operating Income                                     78714000000.0
Operating Expense                                    67984000000.0
Research And Development                             31562000000.0
Selling General And Administration                   36422000000.0
Selling And Marketing Expense                        22912000000.0
General And Administrative Expense                   13510000000.0
Other Gand A                                         13510000000.0
Gross Profit                                        146698000000.0
Cost Of Revenue                                     110939000000.0
Total Revenue                                       257637000000.0
Operating Revenue                                   257637000000.0

                                                       2020-12-31
Tax Effect Of Unusual Items                                   NaN
Tax Rate For Calcs                                            NaN
Normalized EBITDA                                             NaN
Total Unusual Items                                           NaN
Total Unusual Items Excluding Goodwill                        NaN
Net Income From Continuing Operation Net Minori...            NaN
Reconciled Depreciation                                       NaN
Reconciled Cost Of Revenue                                    NaN
EBITDA                                                        NaN
EBIT                                                          NaN
Net Interest Income                                           NaN
Interest Expense                                              NaN
Interest Income                                               NaN
Normalized Income                                             NaN
Net Income From Continuing And Discontinued Ope...            NaN
Total Expenses                                                NaN
Total Operating Income As Reported                            NaN
Diluted Average Shares                              13740560000.0
Basic Average Shares                                13616320000.0
Diluted EPS                                                2.9305
Basic EPS                                                  2.9575
Diluted NI Availto Com Stockholders                           NaN
Net Income Common Stockholders                                NaN
Net Income                                                    NaN
Net Income Including Noncontrolling Interests                 NaN
Net Income Continuous Operations                              NaN
Tax Provision                                                 NaN
Pretax Income                                                 NaN
Other Income Expense                                          NaN
Other Non Operating Income Expenses                           NaN
Special Income Charges                                        0.0
Earnings From Equity Interest                                 NaN
Gain On Sale Of Security                                      NaN
Net Non Operating Interest Income Expense                     NaN
Interest Expense Non Operating                                NaN
Interest Income Non Operating                                 NaN
Operating Income                                              NaN
Operating Expense                                             NaN
Research And Development                                      NaN
Selling General And Administration                            NaN
Selling And Marketing Expense                                 NaN
General And Administrative Expense                            NaN
Other Gand A                                                  NaN
Gross Profit                                                  NaN
Cost Of Revenue                                               NaN
Total Revenue                                                 NaN
Operating Revenue                                             NaN

In [39]:
#Flujo de caja
cashflow = stock_google.cashflow
balance_sheet = stock_google.balance_sheet
recommendations = stock_google.recommendations
#Balance
print(cashflow, balance_sheet, recommendations)

                                                    2024-12-31  \
Free Cash Flow                                   72764000000.0
Repurchase Of Capital Stock                     -62222000000.0
Repayment Of Debt                               -12701000000.0
Issuance Of Debt                                 13589000000.0
Capital Expenditure                             -52535000000.0
Income Tax Paid Supplemental Data                          NaN
End Cash Position                                23466000000.0
Beginning Cash Position                          24048000000.0
Effect Of Exchange Rate Changes                   -612000000.0
Changes In Cash                                     30000000.0
Financing Cash Flow                             -79733000000.0
Cash Flow From Continuing Financing Activities  -79733000000.0
Net Other Financing Charges                       1154000000.0
Proceeds From Stock Option Exercised            -12190000000.0
Cash Dividends Paid                              -7363000000.0
Common Stock Dividend Paid                       -7363000000.0
Net Common Stock Issuance                       -62222000000.0
Common Stock Payments                           -62222000000.0
Net Issuance Payments Of Debt                      888000000.0
Net Long Term Debt Issuance                        888000000.0
Long Term Debt Payments                         -12701000000.0
Long Term Debt Issuance                          13589000000.0
Investing Cash Flow                             -45536000000.0
Cash Flow From Continuing Investing Activities  -45536000000.0
Net Other Investing Changes                      -2667000000.0
Net Investment Purchase And Sale                 12597000000.0
Sale Of Investment                              104310000000.0
Purchase Of Investment                          -91713000000.0
Net Business Purchase And Sale                   -2931000000.0
Purchase Of Business                             -2931000000.0
Net PPE Purchase And Sale                       -52535000000.0
Purchase Of PPE                                 -52535000000.0
Operating Cash Flow                             125299000000.0
Cash Flow From Continuing Operating Activities  125299000000.0
Change In Working Capital                        -8406000000.0
Change In Other Working Capital                  -1375000000.0
Change In Other Current Assets                   -1397000000.0
Change In Payables And Accrued Expense             257000000.0
Change In Accrued Expense                         -102000000.0
Change In Payable                                  359000000.0
Change In Account Payable                          359000000.0
Change In Receivables                            -5891000000.0
Changes In Account Receivables                   -5891000000.0
Other Non Cash Items                              3419000000.0
Stock Based Compensation                         22785000000.0
Deferred Tax                                     -5257000000.0
Deferred Income Tax                              -5257000000.0
Depreciation Amortization Depletion              15311000000.0
Depreciation And Amortization                    15311000000.0
Amortization Cash Flow                                     NaN
Amortization Of Intangibles                                NaN
Depreciation                                     15311000000.0
Operating Gains Losses                           -2671000000.0
Gain Loss On Investment Securities               -2671000000.0
Net Income From Continuing Operations           100118000000.0

                                                    2023-12-31     2022-12-31  \
Free Cash Flow                                   69495000000.0  60010000000.0
Repurchase Of Capital Stock                     -61504000000.0 -59296000000.0
Repayment Of Debt                               -11550000000.0 -54068000000.0
Issuance Of Debt                                 10790000000.0  52872000000.0
Capital Expenditure                             -32251000000.0 -31485000000.0
Income Tax Paid Supplemental Data                19164000000.0  18892000000.0
End Cash Position                                24048000000.0  21879000000.0
Beginning Cash Position                          21879000000.0  20945000000.0
Effect Of Exchange Rate Changes                   -421000000.0   -506000000.0
Changes In Cash                                   2590000000.0   1440000000.0
Financing Cash Flow                             -72093000000.0 -69757000000.0
Cash Flow From Continuing Financing Activities  -72093000000.0 -69757000000.0
Net Other Financing Charges                          8000000.0     35000000.0
Proceeds From Stock Option Exercised             -9837000000.0  -9300000000.0
Cash Dividends Paid                                        0.0            0.0
Common Stock Dividend Paid                                 0.0            0.0
Net Common Stock Issuance                       -61504000000.0 -59296000000.0
Common Stock Payments                           -61504000000.0 -59296000000.0
Net Issuance Payments Of Debt                     -760000000.0  -1196000000.0
Net Long Term Debt Issuance                       -760000000.0  -1196000000.0
Long Term Debt Payments                         -11550000000.0 -54068000000.0
Long Term Debt Issuance                          10790000000.0  52872000000.0
Investing Cash Flow                             -27063000000.0 -20298000000.0
Cash Flow From Continuing Investing Activities  -27063000000.0 -20298000000.0
Net Other Investing Changes                      -1051000000.0   1589000000.0
Net Investment Purchase And Sale                  6734000000.0  16567000000.0
Sale Of Investment                               87619000000.0  97972000000.0
Purchase Of Investment                          -80885000000.0 -81405000000.0
Net Business Purchase And Sale                    -495000000.0  -6969000000.0
Purchase Of Business                              -495000000.0  -6969000000.0
Net PPE Purchase And Sale                       -32251000000.0 -31485000000.0
Purchase Of PPE                                 -32251000000.0 -31485000000.0
Operating Cash Flow                             101746000000.0  91495000000.0
Cash Flow From Continuing Operating Activities  101746000000.0  91495000000.0
Change In Working Capital                        -3845000000.0  -2235000000.0
Change In Other Working Capital                   1048000000.0    951000000.0
Change In Other Current Assets                   -2143000000.0  -5046000000.0
Change In Payables And Accrued Expense            5083000000.0   4177000000.0
Change In Accrued Expense                         4419000000.0   3470000000.0
Change In Payable                                  664000000.0    707000000.0
Change In Account Payable                          664000000.0    707000000.0
Change In Receivables                            -7833000000.0  -2317000000.0
Changes In Account Receivables                   -7833000000.0  -2317000000.0
Other Non Cash Items                              4330000000.0   3483000000.0
Stock Based Compensation                         22460000000.0  19362000000.0
Deferred Tax                                     -7763000000.0  -8081000000.0
Deferred Income Tax                              -7763000000.0  -8081000000.0
Depreciation Amortization Depletion              11946000000.0  13475000000.0
Depreciation And Amortization                    11946000000.0  13475000000.0
Amortization Cash Flow                                     NaN    641000000.0
Amortization Of Intangibles                                NaN    641000000.0
Depreciation                                     11946000000.0  13475000000.0
Operating Gains Losses                             823000000.0   5519000000.0
Gain Loss On Investment Securities                 823000000.0   5519000000.0
Net Income From Continuing Operations            73795000000.0  59972000000.0

                                                    2021-12-31    2020-12-31
Free Cash Flow                                   67012000000.0           NaN
Repurchase Of Capital Stock                     -50274000000.0           NaN
Repayment Of Debt                               -21435000000.0           NaN
Issuance Of Debt                                 20199000000.0           NaN
Capital Expenditure                             -24640000000.0           NaN
Income Tax Paid Supplemental Data                13412000000.0  4990000000.0
End Cash Position                                20945000000.0           NaN
Beginning Cash Position                          26465000000.0           NaN
Effect Of Exchange Rate Changes                   -287000000.0           NaN
Changes In Cash                                  -5233000000.0           NaN
Financing Cash Flow                             -61362000000.0           NaN
Cash Flow From Continuing Financing Activities  -61362000000.0           NaN
Net Other Financing Charges                        310000000.0           NaN
Proceeds From Stock Option Exercised            -10162000000.0           NaN
Cash Dividends Paid                                        NaN           NaN
Common Stock Dividend Paid                                 NaN           NaN
Net Common Stock Issuance                       -50274000000.0           NaN
Common Stock Payments                           -50274000000.0           NaN
Net Issuance Payments Of Debt                    -1236000000.0           NaN
Net Long Term Debt Issuance                      -1236000000.0           NaN
Long Term Debt Payments                         -21435000000.0           NaN
Long Term Debt Issuance                          20199000000.0           NaN
Investing Cash Flow                             -35523000000.0           NaN
Cash Flow From Continuing Investing Activities  -35523000000.0           NaN
Net Other Investing Changes                        541000000.0           NaN
Net Investment Purchase And Sale                 -8806000000.0           NaN
Sale Of Investment                              129228000000.0           NaN
Purchase Of Investment                         -138034000000.0           NaN
Net Business Purchase And Sale                   -2618000000.0           NaN
Purchase Of Business                             -2618000000.0           NaN
Net PPE Purchase And Sale                       -24640000000.0           NaN
Purchase Of PPE                                 -24640000000.0           NaN
Operating Cash Flow                              91652000000.0           NaN
Cash Flow From Continuing Operating Activities   91652000000.0           NaN
Change In Working Capital                        -1523000000.0           NaN
Change In Other Working Capital                    149000000.0           NaN
Change In Other Current Assets                   -1846000000.0           NaN
Change In Payables And Accrued Expense            9269000000.0           NaN
Change In Accrued Expense                         8986000000.0           NaN
Change In Payable                                  283000000.0           NaN
Change In Account Payable                          283000000.0           NaN
Change In Receivables                            -9095000000.0           NaN
Changes In Account Receivables                   -9095000000.0           NaN
Other Non Cash Items                              -213000000.0           NaN
Stock Based Compensation                         15376000000.0           NaN
Deferred Tax                                      1808000000.0           NaN
Deferred Income Tax                               1808000000.0           NaN
Depreciation Amortization Depletion              12441000000.0           NaN
Depreciation And Amortization                    12441000000.0           NaN
Amortization Cash Flow                             886000000.0   792000000.0
Amortization Of Intangibles                        886000000.0   792000000.0
Depreciation                                     11555000000.0           NaN
Operating Gains Losses                          -12270000000.0           NaN
Gain Loss On Investment Securities              -12270000000.0           NaN
Net Income From Continuing Operations            76033000000.0           NaN                                                         2024-12-31  \
Treasury Shares Number                                       NaN
Ordinary Shares Number                             12211000000.0
Share Issued                                       12211000000.0
Total Debt                                         25461000000.0
Tangible Book Value                               293199000000.0
...                                                          ...
Allowance For Doubtful Accounts Receivable          -879000000.0
Gross Accounts Receivable                          53219000000.0
Cash Cash Equivalents And Short Term Investments   95657000000.0
Other Short Term Investments                       72191000000.0
Cash And Cash Equivalents                          23466000000.0

                                                      2023-12-31  \
Treasury Shares Number                                       0.0
Ordinary Shares Number                             12460000000.0
Share Issued                                       12460000000.0
Total Debt                                         27121000000.0
Tangible Book Value                               254181000000.0
...                                                          ...
Allowance For Doubtful Accounts Receivable          -771000000.0
Gross Accounts Receivable                          48735000000.0
Cash Cash Equivalents And Short Term Investments  110916000000.0
Other Short Term Investments                       86868000000.0
Cash And Cash Equivalents                          24048000000.0

                                                      2022-12-31  \
Treasury Shares Number                                       NaN
Ordinary Shares Number                             12849000000.0
Share Issued                                       12849000000.0
Total Debt                                         29679000000.0
Tangible Book Value                               227184000000.0
...                                                          ...
Allowance For Doubtful Accounts Receivable          -754000000.0
Gross Accounts Receivable                          41012000000.0
Cash Cash Equivalents And Short Term Investments  113762000000.0
Other Short Term Investments                       91883000000.0
Cash And Cash Equivalents                          21879000000.0

                                                      2021-12-31 2020-12-31
Treasury Shares Number                                       NaN        NaN
Ordinary Shares Number                             13242420000.0        NaN
Share Issued                                       13242420000.0        NaN
Total Debt                                         28395000000.0        NaN
Tangible Book Value                               227262000000.0        NaN
...                                                          ...        ...
Allowance For Doubtful Accounts Receivable          -550000000.0        NaN
Gross Accounts Receivable                          39854000000.0        NaN
Cash Cash Equivalents And Short Term Investments  139649000000.0        NaN
Other Short Term Investments                      118704000000.0        NaN
Cash And Cash Equivalents                          20945000000.0        NaN

[75 rows x 5 columns]   period  strongBuy  buy  hold  sell  strongSell
0     0m         14   38    12     0           0
1    -1m         15   38    12     0           0
2    -2m         15   36    12     0           0
3    -3m         16   36    11     0           0

In [61]:
# Crear un objeto Ticker para Apple
stock_multi = yf.Tickers(['AAPL', 'GOOGL', 'AMZN' ])
#Cargamos datos de precios hist√≥ricos de activos
df_multi = stock_multi.history(period="1mo")
#DF info
print(df_multi.info())
df_multi

[*********************100%***********************]  3 of 3 completed

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 21 entries, 2025-02-26 to 2025-03-26
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (Close, AAPL)          21 non-null     float64
 1   (Close, AMZN)          21 non-null     float64
 2   (Close, GOOGL)         21 non-null     float64
 3   (Dividends, AAPL)      21 non-null     float64
 4   (Dividends, AMZN)      21 non-null     float64
 5   (Dividends, GOOGL)     21 non-null     float64
 6   (High, AAPL)           21 non-null     float64
 7   (High, AMZN)           21 non-null     float64
 8   (High, GOOGL)          21 non-null     float64
 9   (Low, AAPL)            21 non-null     float64
 10  (Low, AMZN)            21 non-null     float64
 11  (Low, GOOGL)           21 non-null     float64
 12  (Open, AAPL)           21 non-null     float64
 13  (Open, AMZN)           21 non-null     float64
 14  (Open, GOOGL)          21 non-null     float64
 15  (Stock Splits, AAPL)   21 non-null     float64
 16  (Stock Splits, AMZN)   21 non-null     float64
 17  (Stock Splits, GOOGL)  21 non-null     float64
 18  (Volume, AAPL)         21 non-null     int64
 19  (Volume, AMZN)         21 non-null     int64
 20  (Volume, GOOGL)        21 non-null     int64
dtypes: float64(18), int64(3)
memory usage: 3.6 KB
None

Price            Close                         Dividends             \
Ticker            AAPL        AMZN       GOOGL      AAPL AMZN GOOGL
Date
2025-02-26  240.360001  214.350006  172.531296       0.0  0.0   0.0
2025-02-27  237.300003  208.740005  168.306168       0.0  0.0   0.0
2025-02-28  241.839996  212.279999  170.084106       0.0  0.0   0.0
2025-03-03  238.029999  205.020004  166.817871       0.0  0.0   0.0
2025-03-04  235.929993  203.800003  170.723373       0.0  0.0   0.0
2025-03-05  235.740005  208.360001  172.820969       0.0  0.0   0.0
2025-03-06  235.330002  200.699997  172.151733       0.0  0.0   0.0
2025-03-07  239.070007  199.250000  173.660004       0.0  0.0   0.0
2025-03-10  227.479996  194.539993  165.869995       0.0  0.0   0.2
2025-03-11  220.839996  196.589996  164.039993       0.0  0.0   0.0
2025-03-12  216.979996  198.889999  167.110001       0.0  0.0   0.0
2025-03-13  209.679993  193.889999  162.759995       0.0  0.0   0.0
2025-03-14  213.490005  197.949997  165.490005       0.0  0.0   0.0
2025-03-17  214.000000  195.740005  164.289993       0.0  0.0   0.0
2025-03-18  212.690002  192.820007  160.669998       0.0  0.0   0.0
2025-03-19  215.240005  195.539993  163.889999       0.0  0.0   0.0
2025-03-20  214.100006  194.949997  162.800003       0.0  0.0   0.0
2025-03-21  218.270004  196.210007  163.990005       0.0  0.0   0.0
2025-03-24  220.729996  203.259995  167.679993       0.0  0.0   0.0
2025-03-25  223.750000  205.710007  170.559998       0.0  0.0   0.0
2025-03-26  221.070007  200.514999  164.895004       0.0  0.0   0.0

Price             High                                 Low  ...              \
Ticker            AAPL        AMZN       GOOGL        AAPL  ...       GOOGL
Date                                                        ...
2025-02-26  244.979996  218.160004  175.877448  239.130005  ...  171.382625
2025-02-27  242.460007  219.970001  174.359194  237.059998  ...  167.746814
2025-02-28  242.089996  212.619995  170.413729  230.199997  ...  166.578150
2025-03-03  244.029999  214.009995  173.170555  236.110001  ...  165.739112
2025-03-04  240.070007  206.800003  173.090642  234.679993  ...  165.609268
2025-03-05  236.550003  209.979996  173.580089  229.229996  ...  168.865517
2025-03-06  237.860001  205.770004  174.608895  233.160004  ...  170.303856
2025-03-07  241.369995  202.270004  174.768727  234.759995  ...  170.074137
2025-03-10  236.160004  196.729996  168.460007  224.220001  ...  163.690002
2025-03-11  225.839996  200.179993  166.750000  217.449997  ...  161.369995
2025-03-12  221.750000  201.520004  167.639999  214.910004  ...  163.529999
2025-03-13  216.839996  198.880005  166.130005  208.419998  ...  162.110001
2025-03-14  213.949997  198.649994  166.490005  209.580002  ...  162.449997
2025-03-17  215.220001  199.000000  166.300003  209.970001  ...  163.669998
2025-03-18  215.149994  194.000000  164.250000  211.490005  ...  156.720001
2025-03-19  218.759995  195.970001  165.869995  213.750000  ...  161.000000
2025-03-20  217.490005  199.320007  164.889999  212.220001  ...  160.960007
2025-03-21  218.839996  196.990005  164.240005  211.279999  ...  160.889999
2025-03-24  221.479996  203.639999  168.320007  218.580002  ...  165.139999
2025-03-25  224.100006  206.210007  170.630005  220.080002  ...  168.320007
2025-03-26  225.020004  206.009995  169.610001  220.470001  ...  164.839996

Price             Open                         Stock Splits             \
Ticker            AAPL        AMZN       GOOGL         AAPL AMZN GOOGL
Date
2025-02-26  244.330002  214.940002  174.868616          0.0  0.0   0.0
2025-02-27  239.410004  218.350006  173.789858          0.0  0.0   0.0
2025-02-28  236.949997  208.649994  168.485941          0.0  0.0   0.0
2025-03-03  241.789993  213.350006  171.732209          0.0  0.0   0.0
2025-03-04  237.710007  200.110001  166.048765          0.0  0.0   0.0
2025-03-05  235.419998  204.800003  170.323845          0.0  0.0   0.0
2025-03-06  234.440002  204.399994  170.333820          0.0  0.0   0.0
2025-03-07  235.110001  199.490005  171.062988          0.0  0.0   0.0
2025-03-10  235.539993  195.600006  168.259995          0.0  0.0   0.0
2025-03-11  223.809998  193.899994  164.910004          0.0  0.0   0.0
2025-03-12  220.139999  200.720001  166.580002          0.0  0.0   0.0
2025-03-13  215.949997  198.169998  166.039993          0.0  0.0   0.0
2025-03-14  211.250000  197.410004  163.270004          0.0  0.0   0.0
2025-03-17  213.309998  198.770004  165.029999          0.0  0.0   0.0
2025-03-18  214.160004  192.520004  163.679993          0.0  0.0   0.0
2025-03-19  214.220001  193.380005  161.759995          0.0  0.0   0.0
2025-03-20  213.990005  193.070007  161.570007          0.0  0.0   0.0
2025-03-21  211.559998  192.899994  161.210007          0.0  0.0   0.0
2025-03-24  221.000000  200.000000  167.070007          0.0  0.0   0.0
2025-03-25  220.770004  203.600006  168.979996          0.0  0.0   0.0
2025-03-26  223.509995  205.835007  168.979996          0.0  0.0   0.0

Price         Volume
Ticker          AAPL      AMZN     GOOGL
Date
2025-02-26  44433600  39120600  35431300
2025-02-27  41153600  40548600  39991000
2025-02-28  56833400  51771700  48130600
2025-03-03  47184000  42948400  40770500
2025-03-04  53798100  60853100  45388000
2025-03-05  47227600  38610100  30954900
2025-03-06  45170400  49863800  28302000
2025-03-07  46273600  59802800  27385800
2025-03-10  72071200  62350900  43604000
2025-03-11  76137400  54002900  39587400
2025-03-12  62547500  43679300  28372400
2025-03-13  61368300  41270800  31756200
2025-03-14  60107600  38096700  31995900
2025-03-17  48073400  47341800  31184300
2025-03-18  42432400  40414900  42074800
2025-03-19  54385400  39442900  34275600
2025-03-20  48862900  38921100  28138500
2025-03-21  94127800  60056900  36625800
2025-03-24  44299500  41625400  30879100
2025-03-25  34493600  31171200  24174400
2025-03-26  23878866  24072232  19330704

[21 rows x 21 columns]

###### Repaso pr√°ctico de modificaci√≥n y manejo de **strings, for, condicionales, funciones lambda, etc**

In [52]:
#Cambiar nombre del DF multiindex a uno solo
print(df_multi.columns)

MultiIndex([(       'Close',  'AAPL'),
            (       'Close',  'AMZN'),
            (       'Close', 'GOOGL'),
            (   'Dividends',  'AAPL'),
            (   'Dividends',  'AMZN'),
            (   'Dividends', 'GOOGL'),
            (        'High',  'AAPL'),
            (        'High',  'AMZN'),
            (        'High', 'GOOGL'),
            (         'Low',  'AAPL'),
            (         'Low',  'AMZN'),
            (         'Low', 'GOOGL'),
            (        'Open',  'AAPL'),
            (        'Open',  'AMZN'),
            (        'Open', 'GOOGL'),
            ('Stock Splits',  'AAPL'),
            ('Stock Splits',  'AMZN'),
            ('Stock Splits', 'GOOGL'),
            (      'Volume',  'AAPL'),
            (      'Volume',  'AMZN'),
            (      'Volume', 'GOOGL')],
           names=['Price', 'Ticker'])

In [53]:
#Generar lista de nuevos nombres
new_colnames = ['_'.join(col) for col in df_multi.columns]
new_colnames

['Close_AAPL',
 'Close_AMZN',
 'Close_GOOGL',
 'Dividends_AAPL',
 'Dividends_AMZN',
 'Dividends_GOOGL',
 'High_AAPL',
 'High_AMZN',
 'High_GOOGL',
 'Low_AAPL',
 'Low_AMZN',
 'Low_GOOGL',
 'Open_AAPL',
 'Open_AMZN',
 'Open_GOOGL',
 'Stock Splits_AAPL',
 'Stock Splits_AMZN',
 'Stock Splits_GOOGL',
 'Volume_AAPL',
 'Volume_AMZN',
 'Volume_GOOGL']

In [64]:
#Asignamos nuevos nombre al DF
df_multi.columns =  new_colnames
print(df_multi.columns)

Index(['Close_AAPL', 'Close_AMZN', 'Close_GOOGL', 'Dividends_AAPL',
       'Dividends_AMZN', 'Dividends_GOOGL', 'High_AAPL', 'High_AMZN',
       'High_GOOGL', 'Low_AAPL', 'Low_AMZN', 'Low_GOOGL', 'Open_AAPL',
       'Open_AMZN', 'Open_GOOGL', 'Stock Splits_AAPL', 'Stock Splits_AMZN',
       'Stock Splits_GOOGL', 'Volume_AAPL', 'Volume_AMZN', 'Volume_GOOGL'],
      dtype='object')

In [65]:
#Close
list_close = [col for col in df_multi.columns if 'Close' in col]
print(list_close)

['Close_AAPL', 'Close_AMZN', 'Close_GOOGL']

In [66]:
#Creaci√≥n de DF close
df_close =  df_multi[list_close]
print(df_close)

            Close_AAPL  Close_AMZN  Close_GOOGL
Date
2025-02-26  240.360001  214.350006   172.531296
2025-02-27  237.300003  208.740005   168.306168
2025-02-28  241.839996  212.279999   170.084106
2025-03-03  238.029999  205.020004   166.817871
2025-03-04  235.929993  203.800003   170.723373
2025-03-05  235.740005  208.360001   172.820969
2025-03-06  235.330002  200.699997   172.151733
2025-03-07  239.070007  199.250000   173.660004
2025-03-10  227.479996  194.539993   165.869995
2025-03-11  220.839996  196.589996   164.039993
2025-03-12  216.979996  198.889999   167.110001
2025-03-13  209.679993  193.889999   162.759995
2025-03-14  213.490005  197.949997   165.490005
2025-03-17  214.000000  195.740005   164.289993
2025-03-18  212.690002  192.820007   160.669998
2025-03-19  215.240005  195.539993   163.889999
2025-03-20  214.100006  194.949997   162.800003
2025-03-21  218.270004  196.210007   163.990005
2025-03-24  220.729996  203.259995   167.679993
2025-03-25  223.750000  205.710007   170.559998
2025-03-26  221.070007  200.514999   164.895004

###### **Transformaci√≥n de formatos de DF y pivoteo: Long- Wide**

* Formatos de Datos: Wide vs Long

**¬øQu√© es Wide?**

- En el formato **wide**, cada variable o categor√≠a aparece como una columna.
- Frecuente en reportes y tablas resumen.

Ejemplo:

| Persona | A√±o_2020 | A√±o_2021 | A√±o_2022 |
|---------|----------|----------|----------|
| Ana     |   10     |    15    |   20     |
| Juan    |   5      |    7     |   10     |


**¬øQu√© es Long?**

- En el formato **long**, los niveles de una variable se codifican en filas.
- Tambien conocido como Tidy:

   Los datos tidy cumplen:
> 1. Cada variable es una columna.
> 2. Cada observaci√≥n es una fila.
> 3. Cada valor est√° en una celda.



Ejemplo Long (tidy):

| Persona | A√±o   | Valor |
|---------|-------|-------|
| Ana     | 2020  | 10    |
| Ana     | 2021  | 15    |
| Ana     | 2022  | 20    |
| Juan    | 2020  | 5     |
| Juan    | 2021  | 7     |
| Juan    | 2022  | 10    |


> **Recomendado para an√°lisis, visualizaci√≥n y modelado.**

**Uso de las funciones `melt()` y  `pivot() `**

In [67]:

df_wide = pd.DataFrame({
                        'Persona': ['Ana', 'Juan'],
                        'A√±o_2020': [10, 5],
                        'A√±o_2021': [15, 7],
                        'A√±o_2022': [20, 10]
                         })

print(df_wide)

NameError: name 'pd' is not defined

In [ ]:
df_long = df_wide.melt(id_vars='Persona',
                       var_name='A√±o',
                       value_name='Valor')

# Limpiamos el nombre de las columnas
df_long['A√±o'] = df_long['A√±o'].str.replace('A√±o_', '')

### 5.4.2 Procedimiento para importar datos de sitios web y APIs (Inegi, Banxico, ADIP)

### 5.4.3 Archivos de Texto y Excel (.txt, .csv, .xlsx y .xls)
### 5.4.4 Archivos Stata, Sql, Spss